CREATE DATABASE JUSTLIFECASESTUDY;

CREATE TABLE `USERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(128) NOT NULL,
  `FULL_NAME` VARCHAR(100) NOT NULL,
  `ROLE` VARCHAR(50) NOT NULL,
  `IS_ACTIVE` bit(1) DEFAULT b'0',
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  `UPDATED_DT` timestamp NULL DEFAULT current_timestamp(),
   PRIMARY KEY (`ID`),
   KEY `USERNAME` (`USERNAME`)
);

CREATE TABLE `VEHICLES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CAR_NAME` VARCHAR(100) NOT NULL,
  `CAR_REG_NUMBER` VARCHAR(10) NOT NULL,
  `IS_ACTIVE` bit(1) DEFAULT b'0',
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  `UPDATED_DT` timestamp NULL DEFAULT current_timestamp(),
   PRIMARY KEY (`ID`),
   KEY `CAR_NAME` (`CAR_NAME`),
   KEY `CAR_REG_NUMBER` (`CAR_REG_NUMBER`)
);


CREATE TABLE `PROFESSIONAL` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PROFESSIONAL_ID` VARCHAR(10) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(10) NOT NULL,
  `SERVICE_TYPE` VARCHAR(20) NOT NULL,
  `IS_ACTIVE` bit(1) DEFAULT b'0',
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  `UPDATED_DT` timestamp NULL DEFAULT current_timestamp(),
   PRIMARY KEY (`ID`),
   KEY `PROFESSIONAL_ID` (`PROFESSIONAL_ID`)
);


INSERT INTO VEHICLES (CAR_NAME, CAR_REG_NUMBER, IS_ACTIVE, CREATED_DT)
VALUES
('Maruti Swift', 'RJ14CA1234', b'1', NOW()),
('Hyundai Creta', 'RJ14CB5678', b'1', NOW()),
('Tata Nexon', 'RJ14CC9012', b'1', NOW()),
('Maruti Baleno', 'RJ14CD3456', b'1', NOW()),
('Kia Seltos', 'RJ14CE7890', b'1', NOW()),
('Hyundai i20', 'RJ14CF1122', b'1', NOW()),
('Mahindra XUV300', 'RJ14CG3344', b'1', NOW()),
('Toyota Innova', 'RJ14CH5566', b'1', NOW()),
('Honda City', 'RJ14CJ7788', b'1', NOW()),
('Renault Kwid', 'RJ14CK9900', b'1', NOW());

INSERT INTO PROFESSIONAL (PROFESSIONAL_ID, NAME, MOBILE_NUMBER, SERVICE_TYPE, IS_ACTIVE, CREATED_DT)
VALUES
('P1001', 'Rohit Sharma', '9876500011', 'CAR_CLEANER', b'1', NOW()),
('P1002', 'Amit Verma', '9876500012', 'CAR_CLEANER', b'1', NOW()),
('P1003', 'Suresh Gupta', '9876500013', 'CAR_CLEANER', b'1', NOW()),
('P1004', 'Vikas Mehra', '9876500014', 'CAR_CLEANER', b'1', NOW()),
('P1005', 'Rahul Jain', '9876500015', 'CAR_CLEANER', b'1', NOW()),
('P1006', 'Deepak Yadav', '9876500016', 'CAR_CLEANER', b'1', NOW()),
('P1007', 'Mohit Chauhan', '9876500017', 'CAR_CLEANER', b'1', NOW()),
('P1008', 'Gaurav Singh', '9876500018', 'CAR_CLEANER', b'1', NOW()),
('P1009', 'Ankit Sharma', '9876500019', 'CAR_CLEANER', b'1', NOW()),
('P1010', 'Nikhil Rathore', '9876500020', 'CAR_CLEANER', b'1', NOW()),

('P1011', 'Sanjay Kumar', '9876500021', 'CAR_CLEANER', b'1', NOW()),
('P1012', 'Jitendra Saini', '9876500022', 'CAR_CLEANER', b'1', NOW()),
('P1013', 'Harish Rao', '9876500023', 'CAR_CLEANER', b'1', NOW()),
('P1014', 'Pawan Kachhwaha', '9876500024', 'CAR_CLEANER', b'1', NOW()),
('P1015', 'Mukesh Bhati', '9876500025', 'CAR_CLEANER', b'1', NOW()),
('P1016', 'Rakesh Nagar', '9876500026', 'CAR_CLEANER', b'1', NOW()),
('P1017', 'Sunil Patidar', '9876500027', 'CAR_CLEANER', b'1', NOW()),
('P1018', 'Vinod Jangid', '9876500028', 'CAR_CLEANER', b'1', NOW()),
('P1019', 'Kamal Kishor', '9876500029', 'CAR_CLEANER', b'1', NOW()),
('P1020', 'Ravindra Singh', '9876500030', 'CAR_CLEANER', b'1', NOW()),

('P1021', 'Mahesh Sharma', '9876500031', 'CAR_CLEANER', b'1', NOW()),
('P1022', 'Lokesh Saini', '9876500032', 'CAR_CLEANER', b'1', NOW()),
('P1023', 'Prakash Yadav', '9876500033', 'CAR_CLEANER', b'1', NOW()),
('P1024', 'Tarun Jain', '9876500034', 'CAR_CLEANER', b'1', NOW()),
('P1025', 'Hemant Singh', '9876500035', 'CAR_CLEANER', b'1', NOW()),
('P1026', 'Jagdish Choudhary', '9876500036', 'CAR_CLEANER', b'1', NOW()),
('P1027', 'Bhupendra Meena', '9876500037', 'CAR_CLEANER', b'1', NOW()),
('P1028', 'Rajesh Prajapat', '9876500038', 'CAR_CLEANER', b'1', NOW()),
('P1029', 'Kishan Gehlot', '9876500039', 'CAR_CLEANER', b'1', NOW()),
('P1030', 'Arvind Kumar', '9876500040', 'CAR_CLEANER', b'1', NOW());
('P1031', 'Ashok Kumar', '9876500041', 'HOME_CLEANER', b'1', NOW());

CREATE TABLE `BOOKINGS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `BOOKING_ID` VARCHAR(20) NOT NULL,
  `CUSTOMER_ID` BIGINT NOT NULL,
  `STARTED_AT` timestamp NULL DEFAULT NULL,
  `DURATION_HOURS` INT DEFAULT 0,
  `PROFESSION_CLEANER_COUNT` INT DEFAULT 0,
  `STATUS` VARCHAR(20) DEFAULT NULL,
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  `UPDATED_DT` timestamp NULL DEFAULT current_timestamp(),
   PRIMARY KEY (`ID`),
   KEY `IDX_BOOKING_ID` (`BOOKING_ID`),
   KEY `IDX_CUSTOMER_ID` (`CUSTOMER_ID`),

   CONSTRAINT `FK_BOOKING_USERS`
     FOREIGN KEY (`CUSTOMER_ID`)
     REFERENCES `USERS`(`ID`)
     ON DELETE CASCADE
);

CREATE TABLE `BOOKING_CLEANERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `BOOKING_ID` BIGINT NOT NULL,
  `PROFESSIONAL_CLEANER_ID` BIGINT NOT NULL,
  `ASSIGNMENT_STATUS` VARCHAR(20) DEFAULT 'ASSIGNED',
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  `UPDATED_DT` timestamp NULL DEFAULT current_timestamp(),
   PRIMARY KEY (`ID`),
   KEY `IDX_BOOKING_ID` (`BOOKING_ID`),
   KEY `IDX_PROFESSIONAL_CLEANER_ID` (`PROFESSIONAL_CLEANER_ID`),

   CONSTRAINT `FK_BOOKING_CLEANERS_APPOINTMENTS`
     FOREIGN KEY (`BOOKING_ID`)
     REFERENCES `BOOKINGS`(`ID`)
     ON DELETE CASCADE,

   CONSTRAINT `FK_BOOKING_CLEANERS_PROFESSIONAL`
     FOREIGN KEY (`PROFESSIONAL_CLEANER_ID`)
     REFERENCES `PROFESSIONAL`(`ID`)
     ON DELETE CASCADE
);

CREATE TABLE `SYSTEM_RULES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `RULE_KEY` VARCHAR(50) NOT NULL UNIQUE,
  `RULE_VALUE` VARCHAR(50) NOT NULL,
  `UPDATED_DT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`ID`)
);

INSERT INTO SYSTEM_RULES (RULE_KEY, RULE_VALUE) VALUES
('WORK_START_TIME', '08:00'),
('WORK_END_TIME', '22:00'),
('MIN_BREAK_MINUTES', '30'),
('WEEKLY_OFF_DAY', 'FRIDAY');


CREATE INDEX IDX_BOOKING_CLEANERS_PROF_TIME
ON BOOKING_CLEANERS (PROFESSIONAL_CLEANER_ID, ASSIGNMENT_STATUS);

CREATE INDEX IDX_BOOKINGS_TIME
ON BOOKINGS (STARTED_AT, DURATION_HOURS, STATUS);